### PR TITLE
Support Ghidra signature format

### PR DESCRIPTION
**Pull request by SpriteOvO**
This PR implements Ghidra signature format as a experimental feature requested in #2.

Since there is no documentation for this format at the moment, the implementation is referred to https://github.com/NationalSecurityAgency/ghidra/issues/5490#issuecomment-1622277250 - The binary sequence of one byte is enclosed in square brackets, and `.` will be treated as a wildcard.

To use this experimental feature, define the configuration macro `SIGMATCH_EXPERIMENTAL_ENABLE_GHIDRA_SIGNATURE_FORMAT` before including `sigmatch.hpp`.

---

Breaking changes:

- `enum class byte_match_mode` has been removed.
- Member function `sig_byte::match_mode()` has been removed.

New public items:

- Constructors `sig_byte::sig_byte(std::byte value, std::byte mask)` and `sig_byte::sig_byte(unsigned char value, unsigned char mask)` is added.
- Member functions `sig_byte::value()` and `sig_byte::mask()` is added.

### CODE REVIEW

**Comment by SpriteOvO** [comment]
@MattMills Could you try this PR to see if it works well?

**Comment by MattMills** [comment]
Rebuilt with the new signatures and seems to work great, thanks!

**Comment by MattMills** [comment]
@SpriteOvO just incase you didn't see those comments on this PR ^

**Comment by SpriteOvO** [comment]
> @SpriteOvO just incase you didn't see those comments on this PR ^

I recently moved to a new place physically, and my PC is still on the way, I will merge it after my PC is setup :)

**Pull request merged**
